build:
  stage: build
  image: node:12
  script:
    - npm install
    - npm run-script build
  cache:
    paths:
      - ./node_modules
  artifacts:
    expire_in: 1 hour
    paths:
      - dist/my-app
  only:
    - master
tests:
  stage: tests
  image: node:12
    script:
      - sudo npm install
      - sudo npm test --no-watch --no-progress --browsers=ChromeHeadlessCI --watchAll=false
    cache:
      paths:
        - ./node_modules
    only:
      master